HEADERS += src/documenttemplate.h \
    src/exception.h \
    src/fields/fieldcontroller.h \
    src/fields/fieldcreationdialog.h \
    src/fields/field.h \
    src/fields/fieldxmlconvertor.h \
    src/fields/table/tableaddrowcolumndialog.h \
    src/fields/table/tablefieldcontroller.h \
    src/fields/table/tablefieldcreationdialog.h \
    src/fields/table/tablefield.h \
    src/fields/table/tablefieldwidget.h \
    src/fields/table/tablefieldxmlconvertor.h \
    src/fields/text/textfieldcontroller.h \
    src/fields/text/textfieldcreationdialog.h \
    src/fields/text/textfield.h \
    src/fields/text/textfieldwidget.h \
    src/fields/text/textfieldxmlconvertor.h \
    src/sources/source.h \
    src/sources/sourcepool.h \
    src/sources/sourceswidget.h \
    src/sources/table/tablesource.h \
    src/template/templateeditor.h \
    src/template/templatelayoutexceptions.h \
    src/template/templatelayout.h \
    src/template/templatelayoutitem.h \
    src/template/templatesourcemanager.h \
    src/template/templatesourcesexceptions.h \
    src/template/templatesourcesmanager.h \
    src/template/templateview.h \
    src/template/templateviewmode.h \
    src/fieldtools.h \
    src/fitwidthmode.h \
    src/page.h \
    src/pagesettingsdialog.h \
    src/pagetools.h \
    src/settings.h \
    src/strongintvalidator.h \
    src/typeselectiondialog.h \
    src/xmlconvertor.h \
    src/fields/fieldsettingswidget.h \
    src/fields/formatfieldsettingswidget.h \
    src/fields/commonfieldsettingswidget.h \
    src/fields/textrenderinfo.h \
    src/fields/textitem.h \
    src/sources/sourcedialog.h \
    src/sources/sourcefactory.h \
    src/sources/table/tablesourcefactory.h \
    src/sources/table/tablesourcedialog.h \
    src/template/sourcenamevalidator.h \
    src/sources/table/xml/xmltablesource.h \
    src/sources/table/xml/xmltablesourcedialog.h \
    src/sources/table/xml/xmltablesourcefactory.h \
    src/sources/sourcexmlconvertor.h \
    src/sources/table/tablesourcexmlconvertor.h \
    src/sources/table/xml/xmltablesourcexmlconvertor.h \
    src/sources/sourcepool_t.h \
    src/sources/sourcepool_t-inl.h \
    src/sources/text/textsource.h \
    src/sources/text/textsourcedialog.h \
    src/sources/text/textsourcefactory.h \
    src/sources/text/textsourcexmlconvertor.h \
    src/sources/text/xml/xmltextsource.h \
    src/sources/text/xml/xmltextsourcedialog.h \
    src/sources/text/xml/xmltextsourcefactory.h \
    src/sources/text/xml/xmltextsourcexmlconvertor.h \
    src/template/templateformatsettingsdialog.h
SOURCES += src/fields/fieldcontroller.cpp \
    src/fields/field.cpp \
    src/fields/fieldxmlconvertor.cpp \
    src/fields/table/tableaddrowcolumndialog.cpp \
    src/fields/table/tablefieldcontroller.cpp \
    src/fields/table/tablefield.cpp \
    src/fields/table/tablefieldcreationdialog.cpp \
    src/fields/table/tablefieldwidget.cpp \
    src/fields/table/tablefieldxmlconvertor.cpp \
    src/fields/text/textfieldcontroller.cpp \
    src/fields/text/textfield.cpp \
    src/fields/text/textfieldcreationdialog.cpp \
    src/fields/text/textfieldwidget.cpp \
    src/fields/text/textfieldxmlconvertor.cpp \
    src/sources/sourceswidget.cpp \
    src/sources/table/tablesource.cpp \
    src/template/templateeditor.cpp \
    src/template/templatelayout.cpp \
    src/template/templatesourcesmanager.cpp \
    src/template/templateview.cpp \
    src/template/templateviewmode.cpp \
    src/documenttemplate.cpp \
    src/fieldtools.cpp \
    src/fitwidthmode.cpp \
    src/main.cpp \
    src/page.cpp \
    src/pagesettingsdialog.cpp \
    src/pagetools.cpp \
    src/settings.cpp \
    src/typeselectiondialog.cpp \
    src/xmlconvertor.cpp \
    src/fields/fieldcreationdialog.cpp \
    src/fields/fieldsettingswidget.cpp \
    src/fields/commonfieldsettingswidget.cpp \
    src/fields/formatfieldsettingswidget.cpp \
    src/fields/textrenderinfo.cpp \
    src/fields/textitem.cpp \
    src/sources/sourcedialog.cpp \
    src/sources/table/tablesourcefactory.cpp \
    src/sources/table/tablesourcedialog.cpp \
    src/template/sourcenamevalidator.cpp \
    src/sources/table/xml/xmltablesourcefactory.cpp \
    src/sources/table/xml/xmltablesourcedialog.cpp \
    src/sources/table/xml/xmltablesource.cpp \
    src/sources/table/xml/xmltablesourcexmlconvertor.cpp \
    src/sources/text/textsource.cpp \
    src/sources/text/textsourcedialog.cpp \
    src/sources/text/textsourcefactory.cpp \
    src/sources/text/xml/xmltextsource.cpp \
    src/sources/text/xml/xmltextsourcedialog.cpp \
    src/sources/text/xml/xmltextsourcefactory.cpp \
    src/sources/text/xml/xmltextsourcexmlconvertor.cpp \
    src/template/templateformatsettingsdialog.cpp
QT += xml \
    xmlpatterns \
    opengl \
    gui \
    widgets \
    printsupport
TRANSLATIONS += interface_ru.ts \
    interface_en.ts
RESOURCES += doc_template.qrc
QMAKE_CXXFLAGS += --std=c++0x
